name: Test

on: push

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Test script
        run: |
          chmod +x ${{ github.workspace }}/dicerobot-deployment-ubuntu.sh
          printf "10000\npassword\ny\n" | sudo ${{ github.workspace }}/dicerobot-deployment-ubuntu.sh
        shell: bash
